baseURL = "https://example.com"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]
theme = "hugo-product-launch"
title = "DVG - Full-stack developer"
[markup.goldmark.renderer]
hardWraps = true
[params]
copyright = "© Dovydas Van Gucht."
description = "You don't even know what we can do for you!"
favicon = "/favicon-32x32.png"
hidedesignbyline = false
images = ["images/share-image.png"]
title = "Dovydas Van Gucht - Full-stack developer"
[params.meta]
keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
